
spring:
  mail: 
    host: smtp.gmail.com
    port: 587
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    required: true
                    enable: true
    username: gise.developer@gmail.com
    password: 34504397
    
  datasource: 
    url: jdbc:mysql://localhost:3306/foro_yoteambien?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
server:
  error:
    whitelabel:
      enabled: false
# debuguea y muestra el detalle del error
# logging.level.org.springframework.web: DEBUG
# logging.level.org.hibernate: ERROR